// <auto-generated />
namespace SashaSrinivas_HospitalProject_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add3));
        
        string IMigrationMetadata.Id
        {
            get { return "202103250457451_add3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
